<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FormatFusion.Core\FormatFusion.Core.csproj" />
    <PackageReference Include="FFMpegCore" Version="5.1.0" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.*" />
    <PackageReference Include="SharpCompress" Version="0.39.0" />
    <PackageReference Include="SevenZipExtractor" Version="1.0.17" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
    <PackageReference Include="DocX" Version="4.*" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>
</Project>
